apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp-dev-test-cicd-manual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: "thin-csi"
  volumeMode: Filesystem
